let KEYWORDS = [];
let ENABLE = true;
let SHOW_BLOCKED_KEYWORD = false;
/**
 * @type {{keyword: string; regex: RegExp}[]}
 */
let REGEXES = [];

// Invincible Somehow Got EVEN BETTER!?!? - Fireside Discussion

const BACKDROP_CLASSNAME = "a3r545t44t5_no_spoiler_backdrop";

const HOME_SCREEN_TAG = "ytd-rich-item-renderer";
const SEARCH_SCREEN_TAG = "ytd-video-renderer";
const VIDEO_SCREEN_TAG = "ytd-compact-video-renderer";
const VIDEO_SCREEN_TAG2 = x => x.querySelectorAll("yt-lockup-view-model");
const SHORTS_COMPONENT_TAG = "ytm-shorts-lockup-view-model-v2"

const VISIBLE_ICON = `<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
<title>Hide Video Card</title>
<path fill="inherit" d="M16 6c-6.979 0-13.028 4.064-16 10 2.972 5.936 9.021 10 16 10s13.027-4.064 16-10c-2.972-5.936-9.021-10-16-10zM23.889 11.303c1.88 1.199 3.473 2.805 4.67 4.697-1.197 1.891-2.79 3.498-4.67 4.697-2.362 1.507-5.090 2.303-7.889 2.303s-5.527-0.796-7.889-2.303c-1.88-1.199-3.473-2.805-4.67-4.697 1.197-1.891 2.79-3.498 4.67-4.697 0.122-0.078 0.246-0.154 0.371-0.228-0.311 0.854-0.482 1.776-0.482 2.737 0 4.418 3.582 8 8 8s8-3.582 8-8c0-0.962-0.17-1.883-0.482-2.737 0.124 0.074 0.248 0.15 0.371 0.228v0zM16 13c0 1.657-1.343 3-3 3s-3-1.343-3-3 1.343-3 3-3 3 1.343 3 3z"></path>
</svg>
`;
const HIDDEN_ICON = `<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
<title>Show Video Card</title>
<path fill="inherit" d="M29.561 0.439c-0.586-0.586-1.535-0.586-2.121 0l-6.318 6.318c-1.623-0.492-3.342-0.757-5.122-0.757-6.979 0-13.028 4.064-16 10 1.285 2.566 3.145 4.782 5.407 6.472l-4.968 4.968c-0.586 0.586-0.586 1.535 0 2.121 0.293 0.293 0.677 0.439 1.061 0.439s0.768-0.146 1.061-0.439l27-27c0.586-0.586 0.586-1.536 0-2.121zM13 10c1.32 0 2.44 0.853 2.841 2.037l-3.804 3.804c-1.184-0.401-2.037-1.521-2.037-2.841 0-1.657 1.343-3 3-3zM3.441 16c1.197-1.891 2.79-3.498 4.67-4.697 0.122-0.078 0.246-0.154 0.371-0.228-0.311 0.854-0.482 1.776-0.482 2.737 0 1.715 0.54 3.304 1.459 4.607l-1.904 1.904c-1.639-1.151-3.038-2.621-4.114-4.323z"></path>
<path fill="inherit" d="M24 13.813c0-0.849-0.133-1.667-0.378-2.434l-10.056 10.056c0.768 0.245 1.586 0.378 2.435 0.378 4.418 0 8-3.582 8-8z"></path>
<path fill="inherit" d="M25.938 9.062l-2.168 2.168c0.040 0.025 0.079 0.049 0.118 0.074 1.88 1.199 3.473 2.805 4.67 4.697-1.197 1.891-2.79 3.498-4.67 4.697-2.362 1.507-5.090 2.303-7.889 2.303-1.208 0-2.403-0.149-3.561-0.439l-2.403 2.403c1.866 0.671 3.873 1.036 5.964 1.036 6.978 0 13.027-4.064 16-10-1.407-2.81-3.504-5.2-6.062-6.938z"></path>
</svg>
`;

/**
 * 
 * @param {string} text 
 */
function matches(text) {
  if (!text) return false;
  for (let regex of REGEXES) {
    if (text.search(regex.regex) != -1) {
      return { match: true, regex: regex };
    }
  }
  return { match: false };
}

/**
 * 
 * @param {string} text 
 * @returns {string}
 */
function cleanText(text) {
  if (!text) return text;
  if (typeof text === "string" || text instanceof String) {
    return text.replace("\n", "").replace(/\s+/gim, " ");
  }
  return text;
}

/**
 * 
 * @param {HTMLElement} el 
 * @param {string} selector 
 */
function queryParentElement(el, selector) {
  if (!el) return el;
  if (el.parentElement?.querySelector(selector)) return el;
  else return queryParentElement(el.parentElement, selector);
}

/**
 * @param {HTMLElement} parentElement 
 * @returns {HTMLButtonElement}
 */
function createToogleVisibilityButton(parentElement) {
  const button = document.createElement("button");

  // Add our targeted CSS class
  button.className = `${BACKDROP_CLASSNAME}-toggle-btn`;

  // YouTube-style button aesthetics
  Object.assign(button.style, {
    background: "rgba(0, 0, 0, 0.6)", // Dark translucent pill/circle
    border: "none",
    color: "#f1f1f1", // YouTube standard off-white
    fill: "#f1f1f1",
    cursor: "pointer",
    borderRadius: "50%", // Circular button
    padding: "8px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "background-color 0.2s ease",
    width: "40px",
    height: "40px"
  });

  const formatIcon = (svgString) => svgString.replace('width="32" height="32"', 'width="20" height="20"');

  button.addEventListener("mouseenter", () => button.style.backgroundColor = "rgba(0, 0, 0, 0.8)");
  button.addEventListener("mouseleave", () => button.style.backgroundColor = "rgba(0, 0, 0, 0.6)");

  const isRevealed = parentElement.classList.contains("is-revealed");
  button.innerHTML = isRevealed ? formatIcon(VISIBLE_ICON) : formatIcon(HIDDEN_ICON);

  button.addEventListener("click", (ev) => {
    ev.preventDefault();
    ev.stopPropagation();

    const parent = button.parentElement;

    parent.classList.toggle("is-revealed");

    const currentlyRevealed = parent.classList.contains("is-revealed");
    button.innerHTML = currentlyRevealed ? formatIcon(VISIBLE_ICON) : formatIcon(HIDDEN_ICON);

    button.title = currentlyRevealed ? "Hide video" : "Show video";
  });

  return button;
}

/**
 * @param {HTMLElement} parent 
 * @param {{regex: RegExp; keyword: string}|undefined} match 
 * @param {string|undefined} borderRadius 
 * @returns {HTMLDivElement}
 */
function newBackdropElement(parent, match, borderRadius) {
  let parentStyles = getComputedStyle(parent);
  let direction = "column";
  let showheader = true;
  if (parseInt(parentStyles.height) < 150) {
    direction = "row";
    showheader = false;
  }
  const element = document.createElement("div");
  element.className = BACKDROP_CLASSNAME;

  Object.assign(element.style, {
    position: "absolute",
    top: "0",
    left: "0",
    width: "100%",
    height: "100%",
    backdropFilter: "blur(12px)",
    backgroundColor: "rgba(0, 0, 0, 0.9)",
    // zIndex: "500",
    display: "flex",
    flexDirection: direction,
    alignItems: "center",
    justifyContent: "center",
    pointerEvents: "all",
    color: "#f1f1f1",
    fontFamily: '"Roboto", "Arial", sans-serif',
    borderRadius: typeof borderRadius === "string" ? borderRadius : "inherit",
    boxSizing: "border-box",
    padding: "16px",
    textAlign: "center"
  });

  const iconWrapper = document.createElement("div");
  iconWrapper.innerHTML = `
    <svg viewBox="0 0 24 24" fill="currentColor" width="28" height="28" style="opacity: 0.8; margin-bottom: 8px;">
      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.42 0-8-3.58-8-8 0-1.85.63-3.55 1.69-4.9L16.9 18.31C15.55 19.37 13.85 20 12 20zm6.31-3.1L7.1 5.69C8.45 4.63 10.15 4 12 4c4.42 0 8 3.58 8 8 0 1.85-.63 3.55-1.69 4.9z"/>
    </svg>
  `;
  if (showheader) element.appendChild(iconWrapper);

  const header = document.createElement("div");
  header.textContent = "Content Hidden";
  header.style.fontSize = "14px";
  header.style.fontWeight = "500";
  header.style.marginBottom = "6px";

  if (showheader) element.appendChild(header);

  if (typeof match !== "undefined" && match.keyword && SHOW_BLOCKED_KEYWORD) {
    const badge = document.createElement("div");
    Object.assign(badge.style, {
      backgroundColor: "rgba(255, 255, 255, 0.15)",
      padding: "4px 10px",
      borderRadius: "16px",
      fontSize: "12px",
      color: "#aaaaaa",
      marginBottom: direction === "column" ? "12px" : "0px",
      whiteSpace: "nowrap",
      overflow: "hidden",
      textOverflow: "ellipsis",
      maxWidth: "90%"
    });
    badge.textContent = `Contains: "${match.keyword}"`;
    badge.title = badge.textContent;
    element.appendChild(badge);
  }

  let button = createToogleVisibilityButton(element);

  if (button.style) {
    // button.style.marginTop = "8px";
  }

  element.appendChild(button);

  return element;
}

/**
 * 
 * @param {HTMLElement} element 
 * @returns 
 */
function blockVideo(element) {
  let channelName = element.querySelector("#channel-name a");
  if (!channelName) {
    // console.log("not a");
    channelName = element.getElementsByTagName("yt-lockup-metadata-view-model");
    if (channelName.length > 0) {
      channelName = channelName[0];
      channelName = channelName.querySelector(".yt-lockup-metadata-view-model-wiz__text-container yt-content-metadata-view-model>div>span");
      // console.log("yes b");
    }
    if (!channelName || channelName === null) {
      // channelName = null;
      let anchors = element.getElementsByTagName("a");
      channelName = Array.from(anchors).find(x => x.href.includes("/@"));
      if (!channelName) {
        // console.log("not c");
        channelName = null;
      }
    }
  }
  // console.log("got channel name", channelName);
  channelName =
    channelName?.textContent || channelName?.text || channelName?.title;
  channelName = cleanText(channelName);
  let videoTitle = element.querySelector("#video-title");
  if (!videoTitle) {
    videoTitle = element.querySelector("h3");
  }
  videoTitle = videoTitle?.textContent || videoTitle?.text || videoTitle?.title;
  videoTitle = cleanText(videoTitle);
  if (!videoTitle) return;

  let match = matches(videoTitle);
  if (!match.match) match = matches(channelName);

  let existingBackdrop = element.querySelector(`.${BACKDROP_CLASSNAME}`); //|| queryParentElement(element, `.${BACKDROP_CLASSNAME}`);
  if (existingBackdrop && !match.match) {
    existingBackdrop.remove();
  }
  if (!match.match || existingBackdrop) return;
  console.log(`Blocking ${channelName} : ${videoTitle} ${element.tagName}`);
  let backdrop = newBackdropElement(element, match.regex);
  element.toggleAttribute(`${BACKDROP_CLASSNAME}-blocked`);
  element.style.position = "relative";
  element.appendChild(backdrop);
}

/**
 * 
 * @param {HTMLElement} element 
 * @returns 
 */
function blockShorts(element) {
  let videoTitle = element;
  videoTitle = videoTitle?.textContent || videoTitle?.text || videoTitle?.title;
  videoTitle = cleanText(videoTitle);
  if (!videoTitle) return;
  let match = matches(videoTitle);
  let existingBackdrop = element.querySelector(`.${BACKDROP_CLASSNAME}`); //|| queryParentElement(element, `.${BACKDROP_CLASSNAME}`);
  if (existingBackdrop && !match.match) {
    existingBackdrop.remove();
  }
  if (!match.match || existingBackdrop) return;
  console.log(`Blocking short : ${videoTitle}`);
  let backdrop = newBackdropElement(element, match.regex);
  element.appendChild(backdrop);
}

/**
 * 
 * @param {HTMLElement} element 
 * @returns 
 */
function blockElement(element) {
  try {
    if (!element) {
      return;
    }
    if (!ENABLE) {
      return;
    }
    if (element.querySelector(`.${BACKDROP_CLASSNAME}`) || element.hasAttribute(`${BACKDROP_CLASSNAME}-blocked`) || element.closest(`[${BACKDROP_CLASSNAME}-blocked]`)) {
      return;
    }
    // if (element.tagName.startsWith("ytm")) blockShorts(element);
    // else blockVideo(element);
    blockVideo(element);
  } catch (err) {
    console.error(err);
  }
}

const targetNode = document;

const observerConfig = {
  childList: true,
  subtree: true,
  attributeOldValue: true,
};

function completeExistingContent() {
  if (!ENABLE) return;
  let homeElements = document.getElementsByTagName(HOME_SCREEN_TAG);
  let searchElements = document.getElementsByTagName(SEARCH_SCREEN_TAG);
  let watchingElements = document.getElementsByTagName(VIDEO_SCREEN_TAG);
  let shortsElements = document.getElementsByTagName(SHORTS_COMPONENT_TAG);
  let watchingElementsV2 = VIDEO_SCREEN_TAG2(document);
  Array.from(homeElements).forEach((element) => blockElement(element));
  Array.from(shortsElements).forEach((element) => blockElement(element));
  Array.from(watchingElementsV2).forEach((element) => blockElement(element));
  Array.from(searchElements).forEach((element) => blockElement(element));
  Array.from(watchingElements).forEach((element) => blockElement(element));
}

const observer = new MutationObserver((mutations, observer) => {
  // if (!ENABLE) return;
  completeExistingContent();
});

function reset() {
  let elements = document.querySelectorAll(`.${BACKDROP_CLASSNAME}`);
  Array.from(elements).forEach((element) => {
    let parent = element.closest(`[${BACKDROP_CLASSNAME}-blocked]`);
    if (parent) {
      parent.toggleAttribute(`${BACKDROP_CLASSNAME}-blocked`);
    }
    element.remove();
  });
  completeExistingContent();
}

/**
 * 
 * @param {string[]} keywords 
 * @param {boolean} enabled 
 */
function update(keywords, enabled, showBlockedKeywords) {
  KEYWORDS = keywords;
  ENABLE = enabled;
  SHOW_BLOCKED_KEYWORD = showBlockedKeywords;
  REGEXES = KEYWORDS.map((keyword) => {
    let regex = keyword.replace(/[^\w\d\s]/gim, ".*");
    regex = regex.replace(/\s+/gim, "[\\s\\.-_]*");
    regex = regex.replace(/\d+/gim, "\\d+");
    regex = `[^\\w\\d]*${regex}`;
    return { keyword, regex: new RegExp(regex, "im") };
  });
  console.log({ REGEXES });
  reset();
}

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.type === "state_sync") {
    sendResponse(true);
    console.log(request.value);
    update(request.value.keywords, request.value.enabled, request.value.showBlockedKeywords);
  } else {
    sendResponse({ error: "Unknown request type" });
  }
});

function fetchState() {
  chrome.runtime.sendMessage(
    {
      type: "tab_reg",
    },
    (response) => {
      console.log(response);
    }
  );
}

fetchState();

observer.observe(targetNode, observerConfig);
